### PR TITLE
Transfer namespaces from xml to xpath

### PR DESCRIPTION
**Pull request by mielvds**
Fix for #118. 

- [ ] Switch XML parsing to iterative and catch namespaces
- [ ] Pass namespaces to xpath execution
- [ ] Add XPath with prefixes test

### CODE REVIEW

**Comment by ArenasGuerreroJulian** [comment]
Thanks @mielvds ,

I think it works perfectly.

**Comment by mielvds** [comment]
Oh thanks, but I didn't test this yet! I was still going to add a unit test

**Comment by ArenasGuerreroJulian** [comment]
I tried executing for your data and mappings but it looks it still fails:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/xml/etree/ElementPath.py", line 370, in iterfind
    selector = _cache[cache_key]
KeyError: ('/premis:object/premis:objectIdentifier/premis:objectIdentifierValue/text()',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/__main__.py", line 51, in <module>
    num_triples += _materialize_mapping_group_to_file(mapping_group, mappings_df, config)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/materializer.py", line 371, in _materialize_mapping_group_to_file
    data = _materialize_mapping_rule(mapping_rule, mappings_df, config)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/materializer.py", line 342, in _materialize_mapping_rule
    data = _get_data(config, mapping_rule, references)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/materializer.py", line 50, in _get_data
    data = get_file_data(mapping_rule, references)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/data_source/data_file.py", line 52, in get_file_data
    return _read_xml(mapping_rule, references)
  File "/home/jarenas/PycharmProjects/morph-kgc/venv/lib/python3.10/site-packages/morph_kgc/data_source/data_file.py", line 204, in _read_xml
    for r in e.findall(element):
  File "/usr/lib/python3.10/xml/etree/ElementPath.py", line 411, in findall
    return list(iterfind(elem, path, namespaces))
  File "/usr/lib/python3.10/xml/etree/ElementPath.py", line 375, in iterfind
    raise SyntaxError("cannot use absolute path on element")
SyntaxError: cannot use absolute path on element
```

I added the blueprint for a test case based on your data and mappings.

**Comment by mielvds** [comment]
@ArenasGuerreroJulian  I think this is a separate issue with an invalid XPath not being catched properly. 
I'll try to fix the text.

**Pull request merged**
